Homework № 1
made-ml-in-prod-2021/asyash26 pull request #2
Opened 2021-05-09 15:11 UTC by asyash26

2021-05-12 11:21 UTC, Ilyua commented
Согласен с самооценкой - 27 баллов

2021-05-23 15:25 UTC, Sergey-Pravdyukov commented
Следую инструкциям в `README.md`. Установил нужное окружение, запускаю `python train_model.py configs/train/rf_train_config.yml`, получаю такой [лог](https://pastebin.com/YJ1D5TBR) ошибки.

2021-05-23 15:29 UTC, Sergey-Pravdyukov commented on ml_project/src/entities/predict_params.py
> +from typing import List
`Unused import statement 'from typing import List' `

2021-05-23 15:29 UTC, Sergey-Pravdyukov commented on ml_project/src/entities/predict_params.py
> +from src.entities.split_params import SplitParams
Эти импорты тоже не используются.

2021-05-23 15:31 UTC, Sergey-Pravdyukov commented on ml_project/src/models/model_eval.py
> +def check_metrics(pipline: Pipeline, preds: np.ndarray,
`pipeline` не используется.

2021-05-23 15:34 UTC, Sergey-Pravdyukov commented on ml_project/src/models/model_eval.py
> +                  true_labels: pd.Series) -> Dict[str, float]:
А что если вместо `Dict[str, float]' использовать конфиг метрик?

2021-05-23 15:38 UTC, Sergey-Pravdyukov commented
Логгирование верхнеуровневое, следовательно малоинформативное. Попробуй логгировать этапы пайплайна внутри самих этапов. Надеюсь, в следующий раз, когда будешь ловить непонятные баги вспомнишь о логгировании. :)

2021-05-23 15:41 UTC, Sergey-Pravdyukov commented on ml_project/tests/end2end_tests/test_make_prediction.py
> +from sklearn.pipeline import Pipeline
Не используются модули. Настрой пожалуйста IDE таким образом, чтобы подсвечивал такие вещи :)

2021-05-23 15:42 UTC, Sergey-Pravdyukov commented on ml_project/tests/end2end_tests/test_make_prediction.py
> +import logging
Тоже не используется.

2021-05-23 15:42 UTC, Sergey-Pravdyukov commented on ml_project/tests/end2end_tests/test_train_pipeline.py
> +from sklearn.pipeline import Pipeline
Не используется.

2021-05-23 15:43 UTC, Sergey-Pravdyukov commented on ml_project/tests/module_tests/test_build_pipelines.py
> +from typing import Union
Не используется.

2021-05-23 15:45 UTC, Sergey-Pravdyukov commented
Пиклы коммитить не лучшая идея.

2021-05-23 15:48 UTC, Sergey-Pravdyukov commented
В целом все что в `./tests/test_data` не очень осмысленно. Конфиги можно использовать из `./configs` с аргументами режимов тестирования и разработки.

2021-05-23 15:49 UTC, Sergey-Pravdyukov commented
`./tests/generate_data`  расширение .py забыла. :)

2021-05-23 15:51 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +@pytest.fixture()
Добавь пожалуйста scope фикстурам. 

Подробнее о scope можно почитать [здесь](https://habr.com/ru/post/448786/).

2021-05-23 15:52 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +import os
Не используется.

2021-05-23 21:12 UTC, Sergey-Pravdyukov commented on ml_project/configs/train/lr_train_config.yml
> +  target_col: "target"
В текущем состоянии конфиг модели выглядит как God  config - конфигурирует вообще все что связано с тренировкой. Если посмотреть внимательнее на конфиги для логистической регрессии и случайного леса, то окажется что они очень похожи. Попробуй их логически декомпозировать.

2021-05-23 21:16 UTC, Sergey-Pravdyukov commented
Трансформер не нашел.

2021-05-23 21:19 UTC, Sergey-Pravdyukov requested changes
Готова усовершенствовать свое решение?

2021-05-27 09:11 UTC, asyash26 commented
Спасибо за ревью. Только сейчас время появилось, чтобы исправить все недочеты. Попробую разобраться.

2021-05-27 17:45 UTC, asyash26 commented on ml_project/configs/train/lr_train_config.yml
> +  target_col: "target"
Я правильно понимаю, что вы имеете в виду общую логику вынести в один конфиг, и отдельно конфигурировать параметры модели?

2021-05-31 19:22 UTC, Sergey-Pravdyukov commented on ml_project/configs/train/lr_train_config.yml
> +  target_col: "target"
Именно так.

2021-05-31 19:50 UTC, Sergey-Pravdyukov approved these changes
Ок, хорошая работа, молодец! 27 баллов

2021-05-31 20:01 UTC, merged